import { NextPage } from "next";
import Head from "next/head";

export default function Index() {
  return (
    <>
      <Head>
        <title>hikarisound</title>
        <meta name="description" content="Generated by Create Next Stack." />
      </Head>
    </>
  );
}

export async function getServerSideProps() {
  return {
    redirect: {
      destination: "/id",
      permanent: false,
    },
  };
  return {
    props: {}, // Will render the page without redirecting
  };
}
